DATABASE_PATH: "C:/development/ai4i-2020-predictive-maintenance/data/equipament-cycles.csv"

COLUMNS:
  - Type
  - Air temperature [K]
  - Process temperature [K]
  - Rotational speed [rpm]
  - Torque [Nm]
  - Tool wear [min]
# TARGET_COLUMN:
  - Machine failure